[project]
name = "demofastapireact"
version = "0.1.0"
description = "A demo Azure Functions project using FastAPI and React"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-functions>=1.24.0",
    "fastapi>=0.129.0",
    "jinja2>=3.1.6",
    "uvicorn>=0.41.0",
]
